### ISSUE TITLE
Nested forms styling inside Series form.

### ISSUE THREAD

**Issue by Moiz1524** [Spl-Global/headway_portal#21]
Follow up instructions:

- Run rails db:migrate VERSION=0
- Pull code from backend_milestone_1
- Run rails db:migrate
- Run rails s

Note:
-> @khizermoeed Please consult to skype design video and then start working. The remove date link inside specific_dates nested form should be replaced with trash icon. In addition to it you also have to design series show page only. A pack of cards showing series lessons, fixtures and other details are fine. Consult with me on this or if any ambiguity rises.

Associated sub-tasks:

- Add icon for Series in sidebar
- Remove Log Out option from sidebar

**Comment by khizermoeed** [comment]
![Screenshot from 2020-02-04 00-17-30](https://user-images.githubusercontent.com/22822496/73683333-e020fc00-46e3-11ea-9123-9a1129559043.png)

**Comment by khizermoeed** [comment]
![Screenshot from 2020-02-04 00-17-35](https://user-images.githubusercontent.com/22822496/73683358-e9aa6400-46e3-11ea-87d5-ad0da0a82cf3.png)
